owner: MinecraftAuthentication
repo: status

sites:
  - name: Site
    url: https://minecraftauth.me/
  - name: Minecraft
    check: "tcp-ping"
    url: $MINECRAFT_SERVER
    port: 25565
  - name: Login
    url: https://authserver.mojang.com/

status-website:
  cname: status.minecraftauth.me
  logoUrl: https://minecraftauth.me/favicon.png
  theme: night
  name: Minecraft Authentication Status
  navbar:
    - title: Home
      href: https://minecraftauth.me
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
